server:
  port: 8081
  address: 0.0.0.0
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: lax
        secure: true

spring:
  application:
    name: tutor-auth
    version: 1.0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}
          yandex:
            client-id: ${YA_CLIENT_ID}
            client-secret: ${YA_CLIENT_SECRET}
            scope: login:avatar, login:info, login:birthday, login:email
            redirect-uri: ${YA_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: login
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    default-schema: ${DB_SCHEMA}
    schemas: ${DB_SCHEMA}
    create-schemas: true
    mixed: true

springdoc:
  api-docs:
    path: /teacher-portal/auth-service/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
  paths-to-match:
    - /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET_KEY:ajscqSVPNj4GNzF+Ln2H6yaE2etWGExa618+TDP96ZE=}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:300000} # 300000
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${USERNAME_MINIO:minio}
  secret-key: ${PASSWORD_MINIO:minio123}
  bucket-name: ${BUCKET_NAME:avatar-images}

origins:
  front: ${FRONT_ORIGIN:http://localhost:3000}